packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  '@eslint/js': ^9.39.2
  '@tailwindcss/postcss': ^4.2.1
  '@tailwindcss/vite': ^4.1.16
  '@tanstack/react-form': ^1.27.7
  '@tanstack/react-query': ^5.90.21
  '@trpc/client': ^11.10.0
  '@trpc/server': ^11.10.0
  '@trpc/tanstack-react-query': ^11.10.0
  '@types/node': ^24.12.0
  eslint: ^9.39.4
  nuqs: ^2.8.8
  prettier: ^3.8.1
  tailwindcss: ^4.2.1
  typescript: ^5.9.3
  vite: ^7.1.12
  zod: ^4.3.6
  zustand: ^5.0.11

catalogs:
  better-auth:
    '@better-auth/expo': ^1.5.4
    better-auth: ^1.5.4
  react19:
    '@types/react': ~19.2.10
    '@types/react-dom': ~19.1.7
    react: ^19.2.4
    react-dom: ^19.2.4

linkWorkspacePackages: true

onlyBuiltDependencies:
  - '@prisma/engines'
  - bufferutil
  - core-js-pure
  - esbuild
  - prisma
  - sharp
  - unrs-resolver

overrides:
  lightningcss: 1.30.1

peerDependencyRules:
  ignoreMissing:
    - '@prettier/plugin-oxc'

publicHoistPattern:
  - '*eslint*'
  - '*prettier*'
